"""Create Symptom table

Revision ID: eab857ac4e5e
Revises: bd41686b4deb
Create Date: 2024-08-09 19:03:45.679791

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eab857ac4e5e"
down_revision = "bd41686b4deb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "symptom",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=240), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("animal_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["animal_id"],
            ["animal.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("symptom", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_symptom_animal_id"), ["animal_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_symptom_date"), ["date"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_symptom_description"), ["description"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("symptom", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_symptom_description"))
        batch_op.drop_index(batch_op.f("ix_symptom_date"))
        batch_op.drop_index(batch_op.f("ix_symptom_animal_id"))

    op.drop_table("symptom")
    # ### end Alembic commands ###
