"""Make medication end date nullable

Revision ID: 112dd71ad76d
Revises: 180b2e5610fd
Create Date: 2025-03-24 12:42:33.442219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112dd71ad76d'
down_revision = '180b2e5610fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
