"""Add Medication table + general DB updates

Revision ID: 180b2e5610fd
Revises: d1cef7342225
Create Date: 2025-03-22 20:56:19.057319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180b2e5610fd'
down_revision = 'd1cef7342225'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('medication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('times_per_day', sa.Integer(), nullable=True),
    sa.Column('frequency_number', sa.Integer(), nullable=True),
    sa.Column('frequency_unit', sa.Enum('day', 'week', 'month', 'year', name='timeunit'), nullable=True),
    sa.Column('duration_number', sa.Integer(), nullable=True),
    sa.Column('duration_unit', sa.Enum('day', 'week', 'month', 'year', name='timeunit'), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(length=750), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medication_animal_id'), ['animal_id'], unique=False)

    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_index('ix_animal_name')

    with op.batch_alter_table('animal_type', schema=None) as batch_op:
        batch_op.drop_index('ix_animal_type_name')
        batch_op.create_unique_constraint('animal_type_name_uq', ['name'])

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_index('ix_appointment_date')
        batch_op.drop_index('ix_appointment_description')
        batch_op.drop_index('ix_appointment_notes')

    with op.batch_alter_table('symptom', schema=None) as batch_op:
        batch_op.drop_index('ix_symptom_date')
        batch_op.drop_index('ix_symptom_description')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_email')
        batch_op.create_unique_constraint('user_email_uq', ['email'])

    with op.batch_alter_table('weight', schema=None) as batch_op:
        batch_op.drop_index('ix_weight_date')
        batch_op.drop_index('ix_weight_weight')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weight', schema=None) as batch_op:
        batch_op.create_index('ix_weight_weight', ['weight'], unique=False)
        batch_op.create_index('ix_weight_date', ['date'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_email_uq', type_='unique')
        batch_op.create_index('ix_user_email', ['email'], unique=1)

    with op.batch_alter_table('symptom', schema=None) as batch_op:
        batch_op.create_index('ix_symptom_description', ['description'], unique=False)
        batch_op.create_index('ix_symptom_date', ['date'], unique=False)

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.create_index('ix_appointment_notes', ['notes'], unique=False)
        batch_op.create_index('ix_appointment_description', ['description'], unique=False)
        batch_op.create_index('ix_appointment_date', ['date'], unique=False)

    with op.batch_alter_table('animal_type', schema=None) as batch_op:
        batch_op.drop_constraint('animal_type_name_uq', type_='unique')
        batch_op.create_index('ix_animal_type_name', ['name'], unique=1)

    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.create_index('ix_animal_name', ['name'], unique=False)

    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medication_animal_id'))

    op.drop_table('medication')
    # ### end Alembic commands ###
