"""Add Weight table

Revision ID: 4ea397985fb4
Revises: af58ffc487ef
Create Date: 2025-03-04 21:56:16.143115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ea397985fb4'
down_revision = 'af58ffc487ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weight', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weight_animal_id'), ['animal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weight_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_weight_weight'), ['weight'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weight', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weight_weight'))
        batch_op.drop_index(batch_op.f('ix_weight_date'))
        batch_op.drop_index(batch_op.f('ix_weight_animal_id'))

    op.drop_table('weight')
    # ### end Alembic commands ###
