"""Add Appointment table

Revision ID: 6e54360f0379
Revises: 4ea397985fb4
Create Date: 2025-03-10 18:14:59.585942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e54360f0379'
down_revision = '4ea397985fb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(length=750), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointment_animal_id'), ['animal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_notes'), ['notes'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointment_notes'))
        batch_op.drop_index(batch_op.f('ix_appointment_description'))
        batch_op.drop_index(batch_op.f('ix_appointment_date'))
        batch_op.drop_index(batch_op.f('ix_appointment_animal_id'))

    op.drop_table('appointment')
    # ### end Alembic commands ###
